In [2]:
import numpy as np

In [3]:
def load_data(filename, path='D:/notebook/cabstone/data/Anno_fine/'):
    f = open(path + filename)
    lines = f.readlines()
    attr = []
    for i in lines:
        attr.append([int(x) for x in i.split()])
        
    return np.array(attr, dtype = int)

In [4]:
def load_attr(filename, path='D:/notebook/cabstone/data/Anno_fine/'):
    f = open(path + filename)
    lines = f.readlines()
    attr_list = []
    for i in lines[2:]:
        attr_list.append(i.split()[0])
    
    return attr_list

In [5]:
def load_cat_data(filename, path='D:/notebook/cabstone/data/Anno_fine/'):
    f = open(path + filename)
    lines = f.readlines()
    attr = np.zeros(len(cat_list), dtype=int)
    for i in lines:
        attr[int(i)] += 1
    return attr

In [6]:
attr_list = load_attr('list_attr_cloth.txt')

In [7]:
train_attr = load_data('train_attr.txt')

In [8]:
val_attr = load_data('val_attr.txt')

In [9]:
test_attr = load_data('test_attr.txt')

In [15]:
len(train_attr) + len(val_attr) + len(test_attr)

20000

In [13]:
sum(train_attr)

array([ 2383,  2329,   938,  1179,   296,  6633,   242,  4269,  2437,
        7294,  1436,  2706,  9858,  5679,  2416,    47,  5858,   835,
        2073,  9469,   292,   124,  1207,  2001,   758, 11241])

In [9]:
np.sum(np.array([sum(train_attr),sum(val_attr),sum(test_attr)]),axis=1)

array([84000, 12000, 24000])

In [10]:
np.sum(np.sum(np.array([sum(train_attr),sum(val_attr),sum(test_attr)]),axis=1))

120000

In [16]:
attr_list

['floral',
 'graphic',
 'striped',
 'embroidered',
 'pleated',
 'solid',
 'lattice',
 'long_sleeve',
 'short_sleeve',
 'sleeveless',
 'maxi_length',
 'mini_length',
 'no_dress',
 'crew_neckline',
 'v_neckline',
 'square_neckline',
 'no_neckline',
 'denim',
 'chiffon',
 'cotton',
 'leather',
 'faux',
 'knit',
 'tight',
 'loose',
 'conventional']

In [17]:
ats = '0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 '.split()

In [18]:
for i in range(len(ats)):
    if ats[i] == '1':
        print(attr_list[i])

solid
long_sleeve
no_dress
crew_neckline
knit
tight


In [35]:
sum(train_attr) + sum(val_attr) + sum(test_attr)

array([ 3402,  3346,  1347,  1667,   414,  9482,   342,  6117,  3474,
       10409,  2029,  3834, 14137,  8086,  3458,    61,  8395,  1194,
        2885, 13604,   406,   189,  1722,  2891,  1069, 16040])

In [37]:
import pandas as pd

In [38]:
pd.DataFrame(index=attr_list, data=np.array(sum(train_attr) + sum(val_attr) + sum(test_attr)).T, columns=['count'])

count
꽃무늬     3402
그래픽     3346
줄무늬     1347
자수      1667
주름       414
솔리드     9482
격자무늬     342
긴소매     6117
반소매     3474
민소매    10409
롱드레스    2029
미니드레스   3834
상/하의   14137
크루넥     8086
브이넥     3458
스퀘어넥      61
목선없음    8395
데님      1194
쉬폰      2885
면      13604
가죽       406
인조       189
니트      1722
타이트한    2891
널널한     1069
평범한    16040

In [49]:
cat_list_ko = load_attr('list_category_cloth_ko.txt')

In [50]:
cat_list = load_attr('list_category_cloth.txt')

In [51]:
train_cat = load_cat_data('train_cate.txt')

In [52]:
val_cat = load_cat_data('val_cate.txt')

In [53]:
test_cat = load_cat_data('test_cate.txt')

In [54]:
len(cat_list),train_cat.shape, val_cat.shape, test_cat.shape

(50, (50,), (50,), (50,))

In [56]:
pd.DataFrame(index=cat_list_ko[1:], data=np.array(train_cat+ val_cat + test_cat).T[1:], columns=['count'])

count
블레이저      13
블라우스     532
봄버      1508
버튼        23
가디건       10
플란넬      918
홀터넥       13
헨리넥        1
후드        66
자켓       289
저지       673
파카        58
피코트       40
판초         4
스웨터       56
탱크       800
티셔츠     1041
상의      2289
터틀넥      775
7부        14
치노         8
팬티        45
컷오프       41
가우초       96
청바지        0
제깅스      502
승마용       48
조거         6
레깅스      294
사롱       331
반바지        3
치마      1160
추리닝     1007
트레이닝복    162
트렁크       83
카프탄       29
케이프        1
코트         0
커버업      157
원피스        2
점프수트    5669
카프탄      503
기모노        9
잠옷       200
원지         0
로브         7
롬퍼         7
셔츠       507
여름용        0

In [143]:
def make_label_file(img_file, bbox, cate, attr, path='D:/Downloads/Category and Attribute Prediction/Anno_fine/',):
    imgs = open(path + img_file).read().splitlines()
    bboxs = open(path + bbox).read().splitlines()
    cates = open(path + cate).read().splitlines()
    attrs = open(path + attr).read().splitlines()
    
    d = list()
    
    for i in range(len(imgs)):
        d.append(f'{imgs[i]} {bboxs[i]} {cates[i]} {attrs[i]}')
        
    with open('merged_'+img_file,'w') as f:
        for item in d:
            f.write('%s\n' % item)

In [144]:
make_label_file('train.txt','train_bbox.txt','train_cate.txt','train_attr.txt')

In [146]:
make_label_file('val.txt','val_bbox.txt','val_cate.txt','val_attr.txt')

In [146]:
make_label_file('test.txt','test_bbox.txt','test_cate.txt','test_attr.txt')

In [147]:
data = open('merged_train.txt', 'r').read().splitlines()

In [153]:
line = data[0]
ss = line.split()

In [154]:
for i in range(len(ss)):
    print(ss[i])

img/Sweet_Crochet_Blouse/img_00000070.jpg
066
075
241
293
3
0
0
0
1
0
0
0
0
0
1
0
0
1
0
0
0
1
0
1
0
0
0
0
0
0
1


In [161]:
d = dict()

In [162]:
for i in cat_list:
    d[i] = len(d)

In [163]:
d

{'Anorak': 0,
 'Blazer': 1,
 'Blouse': 2,
 'Bomber': 3,
 'Button-Down': 4,
 'Cardigan': 5,
 'Flannel': 6,
 'Halter': 7,
 'Henley': 8,
 'Hoodie': 9,
 'Jacket': 10,
 'Jersey': 11,
 'Parka': 12,
 'Peacoat': 13,
 'Poncho': 14,
 'Sweater': 15,
 'Tank': 16,
 'Tee': 17,
 'Top': 18,
 'Turtleneck': 19,
 'Capris': 20,
 'Chinos': 21,
 'Culottes': 22,
 'Cutoffs': 23,
 'Gauchos': 24,
 'Jeans': 25,
 'Jeggings': 26,
 'Jodhpurs': 27,
 'Joggers': 28,
 'Leggings': 29,
 'Sarong': 30,
 'Shorts': 31,
 'Skirt': 32,
 'Sweatpants': 33,
 'Sweatshorts': 34,
 'Trunks': 35,
 'Caftan': 36,
 'Cape': 37,
 'Coat': 38,
 'Coverup': 39,
 'Dress': 40,
 'Jumpsuit': 41,
 'Kaftan': 42,
 'Kimono': 43,
 'Nightdress': 44,
 'Onesie': 45,
 'Robe': 46,
 'Romper': 47,
 'Shirtdress': 48,
 'Sundress': 49}

In [172]:
d2 = dict()
cnt=0
for i in cat_list_ko:
    d2[i]=cnt
    cnt+=1

In [173]:
d2

{'아노락': 0,
 '블레이저': 1,
 '블라우스': 2,
 '봄버': 3,
 '버튼': 4,
 '가디건': 5,
 '플란넬': 6,
 '홀터넥': 7,
 '헨리넥': 8,
 '후드': 9,
 '자켓': 10,
 '저지': 11,
 '파카': 12,
 '피코트': 13,
 '판초': 14,
 '스웨터': 15,
 '탱크': 16,
 '티셔츠': 17,
 '상의': 18,
 '터틀넥': 19,
 '7부': 20,
 '치노': 21,
 '팬티': 22,
 '컷오프': 23,
 '가우초': 24,
 '청바지': 25,
 '제깅스': 26,
 '승마용': 27,
 '조거': 28,
 '레깅스': 29,
 '사롱': 30,
 '반바지': 31,
 '치마': 32,
 '추리닝': 33,
 '트레이닝복': 34,
 '트렁크': 35,
 '카프탄': 42,
 '케이프': 37,
 '코트': 38,
 '커버업': 39,
 '원피스': 40,
 '점프수트': 41,
 '기모노': 43,
 '잠옷': 44,
 '원지': 45,
 '로브': 46,
 '롬퍼': 47,
 '셔츠': 48,
 '여름용': 49}

In [169]:
len(cat_list_ko)

50